### PR TITLE
Fix issue where DEFAULT_CIPHERS is not supported in urrlib3>=2

### PR DESCRIPTION
**Pull request by landryraccoon**

### CODE REVIEW

**Review by CroMarmot — APPROVED** [review]
LGTM

**Comment by alteralt** [comment]
Thanks, it helped me.

**Comment by sberniz** [comment]
Great it worked Thank you

**Review by marshallez — APPROVED** [review]

**Comment by chriss2401** [comment]
Can we merge and release this ?

**Pull request closed without merging**
